- pipeline:
    name: check
    manager: independent
    trigger:
      my_github:
        - event: pull_request
          action:
            - opened
            - changed
            - reopened
    success:
      my_github:
        check: success
    failure:
      my_github:
        check: failure

- job:
    name: zuul-demo-hello
    run: playbooks/hello.yaml
    nodeset:
          nodes: []

- project:
    #name: KARISHRAM/zuul-demo
    check:
      jobs:
        - zuul-demo-hello
